name: Provision gcp
on:
  push:
    branches: [master]
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Clone repo
      - uses: hashicorp/setup-terraform@v3
        name: Get terraform
      - run: ./decrypt.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.PASSPHRASE}}
        name: Decrypt credentials
      - run: terraform init
        name: Terraform init
        env:
          GOOGLE_CREDENTIALS: key.json
      - name: Terraform refresh state
        run: terraform refresh
        env:
          GOOGLE_CREDENTIALS: key.json
      - run: terraform apply -auto-approve
        name: Terraform apply
        env:
          GOOGLE_CREDENTIALS: key.json
